# .circleci/config.yml

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Surge
          command: npx surge dist --domain pixelart-challenge.surge.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
